# Generated by Django 4.2.1 on 2023-06-14 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Block_name", models.CharField(max_length=200, null=True)),
                ("Block_description", models.CharField(max_length=500, null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Type", models.CharField(max_length=200, null=True)),
                ("Amount", models.FloatField(null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course_name", models.CharField(max_length=200, null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Department_description", models.CharField(max_length=500, null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Month", models.DateField(null=True)),
                ("Total_Purchase", models.FloatField(null=True)),
                ("Opening_stock", models.FloatField(null=True)),
                ("Closing_stock", models.FloatField(null=True)),
                ("Net_purchase", models.FloatField(null=True)),
                ("Guest_coupon_charge", models.IntegerField(null=True)),
                ("Total_mess_attendance", models.IntegerField(null=True)),
                ("Total_mess_expenditure", models.FloatField(null=True)),
                ("Pay_per_expense", models.FloatField(null=True)),
                ("Salary", models.FloatField(null=True)),
                ("Pf", models.FloatField(null=True)),
                ("Mis", models.FloatField(null=True)),
                ("Audit_fee", models.FloatField(null=True)),
                ("Printing_Stationary", models.FloatField(null=True)),
                ("Other_expense", models.FloatField(null=True)),
                ("Total_fixed_expenditure", models.FloatField(null=True)),
                ("No_of_inmates", models.IntegerField(null=True)),
                ("Expense_per_inmates", models.FloatField(null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mess_fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Paid_date", models.DateField(null=True)),
                ("No_of_days_present", models.IntegerField(null=True)),
                ("Mess_fee", models.IntegerField(null=True)),
                ("Fine", models.IntegerField(null=True)),
                ("Total", models.IntegerField(null=True)),
                ("Month_year", models.DateField(null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Block_name", models.CharField(max_length=200, null=True)),
                ("Room_number", models.CharField(max_length=200, null=True)),
                ("Rooms_type", models.CharField(max_length=200, null=True)),
                ("Max_accommodation", models.IntegerField(null=True)),
                ("Vaccancy", models.IntegerField(null=True)),
                ("Amount", models.IntegerField(null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Room_type", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=200, null=True)),
                ("Last_name", models.CharField(max_length=200, null=True)),
                ("Address", models.CharField(max_length=500, null=True)),
                ("State", models.CharField(max_length=200, null=True)),
                ("Street", models.CharField(max_length=200, null=True)),
                ("District", models.CharField(max_length=200, null=True)),
                ("Country", models.CharField(max_length=200, null=True)),
                ("Pincode", models.IntegerField(null=True)),
                ("Guardian_name", models.CharField(max_length=200, null=True)),
                ("Student_phone", models.IntegerField(null=True)),
                ("Guardian_phone", models.IntegerField(null=True)),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Religion", models.CharField(max_length=200, null=True)),
                ("Caste", models.CharField(max_length=200, null=True)),
                ("Concession", models.CharField(max_length=200, null=True)),
                ("DOB", models.DateField(null=True)),
                ("Distance_from_home", models.IntegerField(null=True)),
                ("Year_of_admission", models.DateField(null=True)),
                ("Room_type", models.CharField(max_length=200, null=True)),
                ("Room_no", models.IntegerField(null=True)),
                ("Documents", models.FileField(null=True, upload_to="")),
                ("Photo", models.FileField(null=True, upload_to="")),
                ("Course_name", models.CharField(max_length=200, null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Block_name", models.CharField(max_length=200, null=True)),
                ("Category_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                ("Place", models.CharField(max_length=200, null=True)),
                ("Gender", models.CharField(max_length=200, null=True)),
                ("Admission_no", models.IntegerField(null=True)),
                ("Post", models.CharField(max_length=200, null=True)),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.block",
                    ),
                ),
                (
                    "category_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.category",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.course",
                    ),
                ),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Date", models.DateField(null=True)),
                ("Verification_status", models.CharField(max_length=100, null=True)),
                ("Admission_no", models.IntegerField(null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Distance_from_home", models.IntegerField(null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room_rent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Paid_date", models.DateField(null=True)),
                ("Payment_status", models.CharField(max_length=50, null=True)),
                ("Date", models.DateField(null=True)),
                ("fine", models.IntegerField(null=True)),
                ("Total", models.IntegerField(null=True)),
                ("Rent", models.IntegerField(null=True)),
                ("Admission_no", models.IntegerField(null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Room_no", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200, null=True)),
                ("DOB", models.DateField(null=True)),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Phone_no", models.IntegerField(null=True)),
                ("Address", models.CharField(max_length=500, null=True)),
                ("Photo", models.ImageField(upload_to="images/")),
                ("Status", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hod.room_type",
            ),
        ),
        migrations.CreateModel(
            name="Noticeboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200, null=True)),
                ("Content", models.CharField(max_length=500, null=True)),
                ("Date", models.DateField(null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mess_track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Month", models.DateField(null=True)),
                ("Mess_in_date", models.DateField(null=True)),
                ("Mess_out_date", models.DateField(null=True)),
                ("In_or_out", models.CharField(max_length=50, null=True)),
                ("Time", models.DateField(null=True)),
                ("Mess_fees", models.IntegerField(null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "mess",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.mess_fee",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mess_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200, null=True)),
                ("DOB", models.DateField(null=True)),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Phone_no", models.IntegerField(null=True)),
                ("Address", models.CharField(max_length=500, null=True)),
                ("Photo", models.ImageField(upload_to="images/")),
                ("Status", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mess_in_and_out",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("No_of_ins", models.IntegerField(null=True)),
                ("No_of_outs", models.IntegerField(null=True)),
                ("Students_present", models.IntegerField(null=True)),
                ("Date", models.DateField(null=True)),
                ("Block_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.block",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mess_fee",
            name="student",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hod.student"
            ),
        ),
        migrations.CreateModel(
            name="Hod_registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Name", models.CharField(max_length=200, null=True)),
                ("Position", models.CharField(max_length=200, null=True)),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Office_no", models.IntegerField(null=True)),
                ("Contact_no", models.IntegerField(null=True)),
                ("Photo", models.ImageField(upload_to="images/")),
                ("Username", models.CharField(max_length=200, null=True)),
                ("Password1", models.CharField(max_length=200, null=True)),
                ("Password2", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                ("Role", models.CharField(max_length=100)),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Feedback", models.CharField(max_length=500, null=True)),
                ("Date", models.DateField(null=True)),
                ("Feedback_title", models.CharField(max_length=200, null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deallocation_Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Reason", models.CharField(max_length=100, null=True)),
                ("Date", models.DateField(max_length=100, null=True)),
                ("Admission_no", models.IntegerField(null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Course", models.CharField(max_length=200, null=True)),
                ("Payment_status", models.CharField(max_length=50, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "course_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="dpt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hod.department",
            ),
        ),
        migrations.CreateModel(
            name="Coupon_generate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Guest_name", models.CharField(max_length=100, null=True)),
                ("Issued_date", models.DateField(null=True)),
                ("Amount", models.FloatField(null=True)),
                ("Paid_date", models.DateField(null=True)),
                ("Month", models.DateField(null=True)),
                ("Name", models.CharField(max_length=200, null=True)),
                ("Type", models.CharField(max_length=200, null=True)),
                ("Block_name", models.CharField(max_length=200, null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "Coupon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.coupon",
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.block",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(null=True)),
                ("Complaint_description", models.CharField(max_length=500, null=True)),
                (
                    "Reply",
                    models.CharField(default="no reply", max_length=500, null=True),
                ),
                ("Title", models.CharField(max_length=500, null=True)),
                ("Department_name", models.CharField(max_length=200, null=True)),
                ("Block_name", models.CharField(max_length=200, null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Room_no", models.CharField(max_length=200, null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.block",
                    ),
                ),
                (
                    "dpt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.department",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.room",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admission_fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Department", models.CharField(max_length=200, null=True)),
                ("Student_name", models.CharField(max_length=200, null=True)),
                ("Date", models.DateField(null=True)),
                ("Admission_fee", models.IntegerField(null=True)),
                ("Caution_deposit", models.IntegerField(null=True)),
                ("Registration_amenities", models.IntegerField(null=True)),
                ("Mess_advance_fee", models.IntegerField(null=True)),
                ("Total", models.IntegerField(null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.student",
                    ),
                ),
            ],
        ),
    ]
