# Generated by Django 4.2.1 on 2023-06-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0002_hod_student_alter_expenditure_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission_fee",
            name="Admission_fee",
        ),
        migrations.RemoveField(
            model_name="admission_fee",
            name="Date",
        ),
        migrations.RemoveField(
            model_name="admission_fee",
            name="Department",
        ),
        migrations.RemoveField(
            model_name="admission_fee",
            name="Student_name",
        ),
        migrations.RemoveField(
            model_name="admission_fee",
            name="Total",
        ),
        migrations.RemoveField(
            model_name="admission_fee",
            name="student",
        ),
        migrations.AddField(
            model_name="admission_fee",
            name="Amount_to_pay",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="Admission_fees",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="ad_fee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hod.admission_fee",
            ),
        ),
    ]
