# Generated by Django 4.2.1 on 2023-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0003_remove_admission_fee_admission_fee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admission_fee",
            name="Amount_to_pay",
        ),
        migrations.RemoveField(
            model_name="mess_fee",
            name="Fine",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="Total",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="fine",
        ),
        migrations.AddField(
            model_name="admission_fee",
            name="Amount_for_concession",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="admission_fee",
            name="Amount_for_oec",
            field=models.IntegerField(null=True),
        ),
    ]
