# Generated by Django 4.2.1 on 2023-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0004_remove_admission_fee_amount_to_pay_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="Reply",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
