# Generated by Django 4.2.1 on 2023-06-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0005_alter_complaint_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission_fee",
            name="Amount_for_non_concession",
            field=models.IntegerField(null=True),
        ),
    ]
