# Generated by Django 4.2.1 on 2023-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0007_remove_admission_fee_amount_for_non_concession"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission_fee",
            name="Amount_for_non_concession",
            field=models.IntegerField(null=True),
        ),
    ]
