# Generated by Django 4.2.1 on 2023-06-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0009_mess_registration_password1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon_generate",
            old_name="Guest_name",
            new_name="Paid_status",
        ),
        migrations.RenameField(
            model_name="coupon_generate",
            old_name="Coupon",
            new_name="coupon",
        ),
        migrations.RemoveField(
            model_name="coupon_generate",
            name="Paid_date",
        ),
        migrations.CreateModel(
            name="Guest_coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Guest_name", models.CharField(max_length=100, null=True)),
                ("Type", models.CharField(max_length=200, null=True)),
                ("Issued_date", models.DateField(null=True)),
                ("Amount", models.FloatField(null=True)),
                ("Status", models.CharField(max_length=100)),
                (
                    "coupon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hod.coupon",
                    ),
                ),
            ],
        ),
    ]
