# Generated by Django 4.2.1 on 2023-06-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0010_rename_guest_name_coupon_generate_paid_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon_generate",
            name="Department_name",
        ),
        migrations.RemoveField(
            model_name="coupon_generate",
            name="Month",
        ),
        migrations.RemoveField(
            model_name="coupon_generate",
            name="department",
        ),
        migrations.AddField(
            model_name="hod_registration",
            name="Proof",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mess_registration",
            name="Proof",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room_registration",
            name="Proof",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coupon",
            name="Amount",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
