# Generated by Django 4.2.1 on 2023-06-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0012_transient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="category_name",
            new_name="Categoryname",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="First_name",
            new_name="Student_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="Last_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="ad_fee",
        ),
        migrations.AddField(
            model_name="student",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hod.room_type",
            ),
        ),
    ]
