# Generated by Django 4.2.1 on 2023-06-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0013_rename_category_name_student_categoryname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=200, null=True)),
                ("Password", models.CharField(max_length=500, null=True)),
                ("Role", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="log_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hod.login"
            ),
        ),
    ]
