# Generated by Django 4.2.1 on 2023-06-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0015_messcomplaint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="Reply",
            field=models.CharField(default="no reply", max_length=500, null=True),
        ),
    ]
