# Generated by Django 4.2.1 on 2023-07-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0016_alter_complaint_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mess_in_and_out",
            old_name="Date",
            new_name="Date_in",
        ),
        migrations.AddField(
            model_name="mess_in_and_out",
            name="Date_out",
            field=models.DateField(null=True),
        ),
    ]
