# Generated by Django 4.2.1 on 2023-07-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0017_rename_date_mess_in_and_out_date_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mess_in_and_out",
            name="student",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hod.student"
            ),
        ),
        migrations.AlterField(
            model_name="mess_in_and_out",
            name="Date_in",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mess_in_and_out",
            name="Date_out",
            field=models.DateField(blank=True, null=True),
        ),
    ]
