# Generated by Django 4.2.1 on 2023-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0018_mess_in_and_out_student_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mess_in_and_out",
            old_name="Date_in",
            new_name="Date",
        ),
        migrations.RemoveField(
            model_name="mess_in_and_out",
            name="Date_out",
        ),
        migrations.AlterField(
            model_name="mess_track",
            name="Mess_in_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mess_track",
            name="Mess_out_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
