# Generated by Django 4.2.1 on 2023-07-03 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0022_remove_coupon_generate_block_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hod_student",
            name="hod",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hod.hod_registration",
            ),
        ),
    ]
