# Generated by Django 4.2.1 on 2023-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0024_alter_hod_student_hod"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mess_track",
            name="Mess_fees",
        ),
        migrations.RemoveField(
            model_name="mess_track",
            name="Month",
        ),
        migrations.RemoveField(
            model_name="mess_track",
            name="mess",
        ),
        migrations.AddField(
            model_name="mess_track",
            name="Date",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
