# Generated by Django 4.2.1 on 2023-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0025_remove_mess_track_mess_fees_remove_mess_track_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mess_track",
            name="Mess_in_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mess_track",
            name="Mess_out_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="mess_track",
            name="Time",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
