# Generated by Django 4.2.1 on 2023-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0026_alter_mess_track_mess_in_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hod_registration",
            name="Contact_no",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="hod_registration",
            name="Office_no",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="mess_registration",
            name="Phone_no",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="room_registration",
            name="Phone_no",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Guardian_phone",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="Student_phone",
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
