# Generated by Django 4.2.1 on 2023-07-04 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0029_alter_hod_registration_contact_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room_rent",
            old_name="Room_no",
            new_name="Block_name",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="Admission_no",
        ),
        migrations.RemoveField(
            model_name="room_rent",
            name="Paid_date",
        ),
        migrations.AddField(
            model_name="room_rent",
            name="Room_number",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="room_rent",
            name="block",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hod.block"
            ),
        ),
        migrations.AddField(
            model_name="room_rent",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hod.room"
            ),
        ),
    ]
