# Generated by Django 4.2.1 on 2023-07-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0031_alter_student_student_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mess_track",
            name="Block_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mess_track",
            name="Mess_in_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mess_track",
            name="Mess_out_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mess_track",
            name="Month",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="mess_track",
            name="Students_present",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="mess_track",
            name="block",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="hod.block"
            ),
        ),
        migrations.DeleteModel(
            name="Mess_in_and_out",
        ),
    ]
