# Generated by Django 4.2.1 on 2023-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0034_alter_room_fee_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="Vaccancy",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
