# Generated by Django 4.2.1 on 2023-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0035_alter_room_vaccancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="Vaccancy",
            field=models.IntegerField(
                blank=True, default=models.IntegerField(null=True), null=True
            ),
        ),
    ]
