# Generated by Django 4.2.1 on 2023-07-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0037_alter_room_vaccancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenditure",
            name="Year",
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="expenditure",
            name="amt",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hod.guest_coupon",
            ),
        ),
        migrations.AddField(
            model_name="guest_coupon",
            name="End_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="guest_coupon",
            name="Start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="expenditure",
            name="Month",
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="guest_coupon",
            name="Amount",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
