# Generated by Django 4.2.1 on 2023-07-24 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hod", "0039_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="room_rent",
            name="Month",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="transient",
            name="Role",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="Department_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="Student_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="hod_registration",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hostelmanagment_hod_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="login",
            name="Role",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="noticeboard",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hostelmanagment_noticeboard",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room_rent",
            name="Block_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="room_rent",
            name="Department_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="room_rent",
            name="Rent",
            field=models.IntegerField(default=80, null=True),
        ),
        migrations.AlterField(
            model_name="room_rent",
            name="Room_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="room_rent",
            name="Student_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
