# Generated by Django 4.2.1 on 2023-07-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hod", "0041_alter_room_registration_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hod_registration",
            name="Office_no",
        ),
        migrations.AlterField(
            model_name="hod_registration",
            name="Contact_no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
