from django.contrib import admin
from .models import Admission_fee,Mess_track,Room_rent,Room_fee,Deallocation_Request,MessComplaint,Feedback,Login,Student,Room_request,Transient,Coupon_generate,Complaint,Guest_coupon,Department,Hod_student,Category,Course,Noticeboard,Expenditure,Room,Hod_registration,Room_registration,Mess_registration,Coupon,Block,Room_type

# Register your models here.,
admin.site.register(Department)
admin.site.register(Course)
admin.site.register(Noticeboard)
admin.site.register(Hod_registration)
admin.site.register(Hod_student)
admin.site.register(Room_registration)
admin.site.register(Mess_registration)
admin.site.register(Coupon)
admin.site.register(Block)
admin.site.register(Room)
admin.site.register(Room_type)
admin.site.register(Expenditure)
admin.site.register(Category)
admin.site.register(Admission_fee)
admin.site.register(Complaint)
admin.site.register(Transient)
admin.site.register(Login)
admin.site.register(Guest_coupon)
admin.site.register(Coupon_generate)
admin.site.register(Student)
admin.site.register(Room_request)
admin.site.register(Feedback)
admin.site.register(MessComplaint)
admin.site.register(Mess_track)
admin.site.register(Deallocation_Request)
admin.site.register(Room_rent)
admin.site.register(Room_fee)
